config/routes.rb
Facescrape::Application.routes.draw do
  get "posts/index"

  resources :brands
  
  resources :info
  
  match "/posts" => "posts#index"
  
  match "/posts/:id" => "posts#show"

  match "/get_brand_data" => "brands#get_brand_data"

  match "/channel.html" => "channel#index"
  
  root :to => "info#index"
  

end

app/models/brand.rb
class Brand < ActiveRecord::Base
  validates_presence_of :name, :username, :fb_id, :on => :create, :message => "can't be blank"
  
  
end

app/models/info.rb
class Info < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/post_ids.rb
class PostIds < ActiveRecord::Base
  validates_uniqueness_of :post_id, :on => :create, :message => "must be unique"
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
require "koala"
require "facescrape/facescrape"
include Facescrape

class ApplicationController < ActionController::Base
  protect_from_forgery
  
  before_filter :parse_facebook_cookies, :access_token, :setup_global_data

  def parse_facebook_cookies
    @facebook_cookies ||= Koala::Facebook::OAuth.new(Facebook::APP_ID, Facebook::SECRET).get_user_info_from_cookies(cookies)
  end
  
  def access_token
    if @facebook_cookies.kind_of?(Array) || @facebook_cookies.kind_of?(Hash)
      @access_token = @facebook_cookies["access_token"]
      @graph = Koala::Facebook::API.new(@access_token)
    end
  end
  
  def setup_global_data
    # vars = {}
    # var_names = [@graph] # You can put params and anything else really
    # var_names.each do |var|
    #   vars[var.to_s] = session[var]
    # end

    Facescrape::GlobalData.graph = @graph
  end
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  layout nil
  layout 'application', :except => :get_brand_data
  # GET /brands
  # GET /brands.json
  def index
    @brands = Brand.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @brands }
    end
  end

  # GET /brands/1
  # GET /brands/1.json
  def show
    @brand = Brand.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @brand }
    end
  end

  # GET /brands/new
  # GET /brands/new.json
  def new
    @brand = Brand.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @brand }
      format.js
    end
  end

  # GET /brands/1/edit
  def edit
    @brand = Brand.find(params[:id])
  end

  # POST /brands
  # POST /brands.json
  def create
    @brand = Brand.new(params[:brand])

    respond_to do |format|
      if @brand.save
        format.html { redirect_to @brand, notice: 'Brand was successfully created.' }
        format.json { render json: @brand, status: :created, location: @brand }
      else
        format.html { render action: "new" }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /brands/1
  # PUT /brands/1.json
  def update
    @brand = Brand.find(params[:id])

    respond_to do |format|
      if @brand.update_attributes(params[:brand])
        format.html { redirect_to @brand, notice: 'Brand was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1
  # DELETE /brands/1.json
  def destroy
    @brand = Brand.find(params[:id])
    @brand.destroy

    respond_to do |format|
      format.html { redirect_to brands_url }
      format.json { head :ok }
    end
  end
  
  def get_brand_data
    @data = @graph.get_object(params[:search])
    
    respond_to do |format|
      format.html
      format.js
    end
  end
end

app/controllers/channel_controller.rb
class ChannelController < ApplicationController
  caches_page :index
  layout nil
  
  def index
  end

end

app/controllers/info_controller.rb
require "koala"
require "facescrape/facescrape"
include Facescrape

class InfoController < ApplicationController
  
  def index
    begin
      if PostIds.all.length > 0
        @pids = PostIds.order("brand_id ASC, created_at DESC").all
      end
      # @comments = @graph.get_connections("90824638062_10150521227138063", "comments")
    rescue Exception => e
      puts "Exception: #{e}"
      logger.error "#{e}"
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
  def format_websites(sites)
    text = ''
    site_arr = sites.split(/\r\n/)
    site_arr.each do |s|
      if s.start_with?("www")
        s.insert(0, 'http://')
      end
      if s.start_with?("http://")
        text << "#{link_to s, s, :target => '_blank'}<br>"
      end
    end
    text.html_safe
  end
end

app/helpers/channel_helper.rb
module ChannelHelper
end

app/helpers/info_helper.rb
module InfoHelper
  def filter_ids(id, data)
    text = ''
    # ids = Array.new
    data.each do |d|
      if d['id'].start_with?("#{id}_")
        text <<  "#{d['id']}<br>"
      end
    end
    text.html_safe
  end
  
  def total_num_brands
    @brands = "Tracking #{Brand.all.count} Brands"
  end
  
  def total_num_posts
    @posts = "Tracking #{Post.all.count} Posts"
  end
end

app/views/brands/_form.html.erb
<%= form_tag(get_brand_data_path, :method => :get, :remote => true) do %>
	<p>
		<%= text_field_tag :search, params[:search] %>
		<%= submit_tag "Get Data", :name => nil %>
	</p>
<% end %>
<%= form_for(@brand) do |f| %>
  <% if @brand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@brand.errors.count, "error") %> prohibited this brand from being saved:</h2>

      <ul>
      <% @brand.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	<div id="test">
		
	</div>
	<div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
	<div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
	<div class="field">
    <%= f.label "Facebook ID" %><br />
    <%= f.text_field :fb_id, :id => "brand_id" %>
  </div>
	<div class="field">
    <%= f.label :picture %><br />
    <%= f.text_field :picture %>
  </div>
	<div class="field">
    <%= f.label :link %><br />
    <%= f.text_field :link %>
  </div>
	<div class="field">
    <%= f.label :likes %><br />
    <%= f.text_field :likes %>
  </div>
	<div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
	<div class="field">
    <%= f.label :website %><br />
    <%= f.text_area :website, :size => "50x5" %>
  </div>
	<div class="field">
    <%= f.label :personal_info %><br />
    <%= f.text_field :personal_info %>
  </div>
	<div class="field">
    <%= f.label :talking_about_count %><br />
    <%= f.text_field :talking_about_count %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/brands/edit.html.erb
<h1>Editing brand</h1>

<%= render 'form' %>

<%= link_to 'Show', @brand %> |
<%= link_to 'Back', brands_path %>

app/views/brands/get_brand_data.html.erb
<%= raw @data %>

app/views/brands/get_brand_data.js.erb
<% fields = %w{ username name fb_id picture link likes category website personal_info talking_about_count } %>
<% fields.each do |f| %>
	<% if f == 'fb_id'; f = 'id'; end %>
	$("#brand_<%= f %>").val("<%=j raw @data[f] %>");
<% end %>

app/views/brands/index.html.erb
<h1>Listing brands</h1>

<div><%= link_to 'New Brand', new_brand_path %></div>

<div class="info_block">
	<table width="100%">
	  <tr>
	    <th>Name</th>
	    <th>Username</th>
	    <th>Facebook ID</th>
			<th>Picture</th>
	    <th>Link</th>
			<th>Likes</th>
			<th>Category</th>
			<th>Website(s)</th>
			<th>Personal Info</th>
			<th>TAC</th>
			<th></th>
	    <th></th>
	    <th></th>
	  </tr>

	<% @brands.each do |brand| %>
	  <tr>
	    <td><%= brand.name %></td>
	    <td><%= brand.username %></td>
	    <td><%= brand.fb_id %></td>
			<td><%= image_tag(brand.picture) %></td>
			<td><%= link_to brand.link, brand.link, :target => '_blank' %></td>
			<td><%= brand.likes %></td>
			<td><%= brand.category %></td>
			<td><%= format_websites brand.website %></td>
			<td><%= brand.personal_info %></td>
			<td><%= brand.talking_about_count %></td>
	    <td><%= link_to 'Show', brand %></td>
	    <td><%= link_to 'Edit', edit_brand_path(brand) %></td>
	    <td><%= link_to 'Destroy', brand, confirm: 'Are you sure?', method: :delete %></td>
	  </tr>
	<% end %>
	</table>
</div>

app/views/brands/new.html.erb
<h1>New brand</h1>

<%= render 'form' %>

<%= link_to 'Back', brands_path %>

app/views/brands/show.html.erb
<p id="notice"><%= notice %></p>

<table width="100%" border="0" cellspacing="5" cellpadding="5">
	<tr>
		<th>Name:</th>
		<th>Likes:</th>
	</tr>
	<tr>
		<td><%= @brand.name %></td>
		<td><%= @brand.likes %></td>
	</tr>
	<tr>
		<th>Username:</th>
		<th>Category:</th>
	</tr>
	<tr>
		<td><%= @brand.username %></td>
		<td><%= @brand.category %></td>
	</tr>
	<tr>
		<th>Facebook ID:</th>
		<th>Website(s):</th>
	</tr>
	<tr>
		<td><%= @brand.fb_id %></td>
		<td><%= format_websites @brand.website %></td>
	</tr>
	<tr>
		<th>Picture:</th>
		<th>Personal Info:</th>
	</tr>
	<tr>
		<td rowspan="5"><%= image_tag @brand.picture %></td>
		<td><%= @brand.personal_info %></td>
	</tr>
	<tr>
		<th>Talking About Count:</th>
	</tr>
	<tr>
		<td><%= @brand.talking_about_count %></td>
	</tr>
	<tr>
		<th>Link:</th>
	</tr>
	<tr>
		<td><%= link_to @brand.link, @brand.link, :target => '_blank' %></td>
	</tr>
</table>

<%= link_to 'Edit', edit_brand_path(@brand) %> |
<%= link_to 'Back', brands_path %>

app/views/channel/index.html.erb
<script src="//connect.facebook.net/en_US/all.js"></script>

app/views/info/index.html.erb
<div class="info_block">
	<% if @pids.kind_of?(Array) %>
		<div>
			<strong><%= total_num_brands %> | <%= total_num_posts %></strong>	
		</div>
		<% @pids.each do |d| %>
		<ul>
			<%= content_tag :li, "#{d.brand_id}: #{d.post_id}" %>
		</ul>
		<% end %>
	<% else %>
		<%= @pids %>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Facescrape</title>
	  <%= stylesheet_link_tag    "application" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<div id="fb-root"></div>
		<script>
		  window.fbAsyncInit = function() {
		    FB.init({
		      appId      : '<%= Facebook::APP_ID %>', // App ID
		      channelUrl : '//<%= Facebook::CALLBACK %>/channel.html', // Channel File
		      status     : true, // check login status
		      cookie     : true, // enable cookies to allow the server to access the session
		      xfbml      : true  // parse XFBML
		    });

		    // Additional initialization code here
		  };

		  // Load the SDK Asynchronously
		  (function(d){
		     var js, id = 'facebook-jssdk'; if (d.getElementById(id)) {return;}
		     js = d.createElement('script'); js.id = id; js.async = true;
		     js.src = "//connect.facebook.net/en_US/all.js";
		     d.getElementsByTagName('head')[0].appendChild(js);
		   }(document));
		</script>
		
		<% if flash[:notice] %>
			<p class="notice"><%= flash[:notice] %></p>
		<% end %>
		<% if flash[:error] %>
			<p class="error"><%= flash[:error] %></p>
		<% end %>
	
		<div class="nav">
			<%= link_to "Home", root_url %> | <%= link_to "Brands", brands_path %> | <%= link_to "Posts", posts_path %>
		</div>	

		<%= yield %>

	</body>
</html>